### ISSUE TITLE
Properties contain side-effects

### ISSUE THREAD

**Issue by airwareic** [delacruz/MusicPlayer#1]
Hey Jason! Your music player looks good so far- it's well encapsulated and functional. One thing I'd say though is that it's best practice to remove side effects from your properties. Try and see if you can rewrite your properties to only set their encapsulated field and notify listeners of a change. That way subscribers can listen for the property change as part of a separate function. Two examples of properties that have side effects are SelectedArtist and SelectedAlbum.

Also there may be a potential for a NullReferenceException on SelectedArtist. Take a look and see if you can resolve these two issues.

**Comment by delacruz** [comment]
Thanks for the feedback!  I've removed side effects from properties and now handling things in event handlers.  Also added a null check for a case where a given artist may have no albums.

**Comment by airwareic** [comment]
Great! That looks solid. I especially like your use of C# 6 features. Here we use ReactiveUI, which if you're not familiar is an excellent C# toolset that makes writing these kinds of property subscriptions a breeze. It's a more functional paradigm that leverages expressions to allow us to write things like:

```
public class Example
{
    public int _myInt
    {
        get { return _myInt; }
        private set { this.RaiseAndSetIfChanged(ref _myInt, value); }
    }

    private readonly ObservableAsPropertyHelper<int> _myIntPlusOne;
    public int MyIntPlusOne
    {
        get { return _myIntPlusOne.value; }
    }

    public Example()
    {
        _myIntPlusOne = this.WhenAnyValue(ex => ex.MyInt)
            .Select(num => num + 1)
            .ToProperty(this, ex => ex.MyIntPlusOne);

        MyInt = 3;
    }
}
```

So that's a lot of specific syntax to say that I want to create an int, MyInt, which will notify subscribers each time its value changes, and to set up MyIntPlusOne to be a readonly property which subscribes to changes on MyInt and sets itself to MyInt + 1. It's a nice way of managing these dependencies and there are some great tools built in, including ReactiveLists.

Anyway that's how we do it here, there's no need to apply that style to your code!

**Comment by delacruz** [comment]
I had heard of rx on podcasts but hadn't worked with it.  Had to try ReactiveUI, [pretty cool, have a look!](https://github.com/delacruz/MusicPlayer/blob/master/MusicPlayer/Models/Album.cs#L18)  Thanks for the feedback!
